package com.oculusvr.capi;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class EyeRenderDesc extends Structure {
	/** < The eye index this instance corresponds to. */
	public int Eye;
	/** < The field of view. */
	public FovPort Fov;
	/** < Distortion viewport. */
	public OvrRecti DistortedViewport;
	/** < How many display pixels will fit in tan(angle) = 1. */
	public OvrVector2f PixelsPerTanAngleAtCenter;
	/** < Translation to be applied to view matrix for each eye offset. */
	public OvrVector3f HmdToEyeViewOffset;
	public EyeRenderDesc() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("Eye", "Fov", "DistortedViewport", "PixelsPerTanAngleAtCenter", "HmdToEyeViewOffset");
	}
	public EyeRenderDesc(int Eye, FovPort Fov, OvrRecti DistortedViewport, OvrVector2f PixelsPerTanAngleAtCenter, OvrVector3f HmdToEyeViewOffset) {
		super();
		this.Eye = Eye;
		this.Fov = Fov;
		this.DistortedViewport = DistortedViewport;
		this.PixelsPerTanAngleAtCenter = PixelsPerTanAngleAtCenter;
		this.HmdToEyeViewOffset = HmdToEyeViewOffset;
	}
	public EyeRenderDesc(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends EyeRenderDesc implements Structure.ByReference {
		
	};
	public static class ByValue extends EyeRenderDesc implements Structure.ByValue {
		
	};
}
