package com.oculusvr.capi;
import java.util.Arrays;
import java.util.List;

import com.sun.jna.Pointer;
import com.sun.jna.Structure;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class FovPort extends Structure {
	/** < The tangent of the angle between the viewing vector and the top edge of the field of view. */
	public float UpTan;
	/** < The tangent of the angle between the viewing vector and the bottom edge of the field of view. */
	public float DownTan;
	/** < The tangent of the angle between the viewing vector and the left edge of the field of view. */
	public float LeftTan;
	/** < The tangent of the angle between the viewing vector and the right edge of the field of view. */
	public float RightTan;
	public FovPort() {
		super();
	}
	@Override
  protected List<? > getFieldOrder() {
		return Arrays.asList("UpTan", "DownTan", "LeftTan", "RightTan");
	}
	public FovPort(float UpTan, float DownTan, float LeftTan, float RightTan) {
		super();
		this.UpTan = UpTan;
		this.DownTan = DownTan;
		this.LeftTan = LeftTan;
		this.RightTan = RightTan;
	}
	public FovPort(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends FovPort implements Structure.ByReference {
		
	};
	public static class ByValue extends FovPort implements Structure.ByValue {
	    public ByValue(FovPort o) {
	      super(o.UpTan, o.DownTan, o.LeftTan, o.RightTan);
	    }
	};
}
