package com.oculusvr.capi;
import com.oculusvr.capi.OvrLibrary.ovrLogCallback;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class InitParams extends Structure {
	/** < Combination of ovrInitFlags or 0 */
	public int Flags;
	public int RequestedMinorVersion;
	/** < Function pointer or 0 */
	public ovrLogCallback LogCallback;
	/** < Timeout in Milliseconds or 0 */
	public int ConnectionTimeoutMS;
	public InitParams() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("Flags", "RequestedMinorVersion", "LogCallback", "ConnectionTimeoutMS");
	}
	public InitParams(int Flags, int RequestedMinorVersion, ovrLogCallback LogCallback, int ConnectionTimeoutMS) {
		super();
		this.Flags = Flags;
		this.RequestedMinorVersion = RequestedMinorVersion;
		this.LogCallback = LogCallback;
		this.ConnectionTimeoutMS = ConnectionTimeoutMS;
	}
	public InitParams(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends InitParams implements Structure.ByReference {
		
	};
	public static class ByValue extends InitParams implements Structure.ByValue {
		
	};
}
