package com.oculusvr.capi;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PositionTimewarpDesc extends Structure {
	public OvrVector3f[] HmdToEyeViewOffset = new OvrVector3f[2];
	public float NearClip;
	public float FarClip;
	public PositionTimewarpDesc() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("HmdToEyeViewOffset", "NearClip", "FarClip");
	}
	public PositionTimewarpDesc(OvrVector3f HmdToEyeViewOffset[], float NearClip, float FarClip) {
		super();
		if ((HmdToEyeViewOffset.length != this.HmdToEyeViewOffset.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.HmdToEyeViewOffset = HmdToEyeViewOffset;
		this.NearClip = NearClip;
		this.FarClip = FarClip;
	}
	public PositionTimewarpDesc(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends PositionTimewarpDesc implements Structure.ByReference {
		
	};
	public static class ByValue extends PositionTimewarpDesc implements Structure.ByValue {
		
	};
}
