package com.oculusvr.capi;

import java.util.Arrays;
import java.util.List;

import com.sun.jna.Pointer;
import com.sun.jna.Structure;

/**
 * <i>native declaration : /usr/include/stdint.h</i><br>
 * This file was autogenerated by <a
 * href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a
 * href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few
 * opensource projects.</a>.<br>
 * For help, please visit <a
 * href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a
 * href="http://rococoa.dev.java.net/">Rococoa</a>, or <a
 * href="http://jna.dev.java.net/">JNA</a>.
 */
public class RenderAPIConfig extends Structure {
  /** C type : ovrRenderAPIConfigHeader */
  public RenderAPIConfigHeader Header;
  /** C type : uintptr_t[8] */
  public Pointer PlatformData[] = new Pointer[8];

  public RenderAPIConfig() {
    super();
  }

  @Override
  protected List<?> getFieldOrder() {
    return Arrays.asList("Header", "PlatformData");
  }

  /**
   * @param Header
   *          C type : ovrRenderAPIConfigHeader<br>
   * @param PlatformData
   *          C type : uintptr_t[8]
   */
  public RenderAPIConfig(RenderAPIConfigHeader Header, int PlatformData[]) {
    super();
    this.Header = Header;
    if ((PlatformData.length != this.PlatformData.length))
      throw new IllegalArgumentException("Wrong array size !");
    for (int i = 0; i < this.PlatformData.length; ++i) {
      this.PlatformData[i] = Pointer.createConstant(0);
    }
  }

  public RenderAPIConfig(Pointer peer) {
    super(peer);
  }

  public static class ByReference extends RenderAPIConfig implements Structure.ByReference {

  };

  public static class ByValue extends RenderAPIConfig implements Structure.ByValue {

  };
}
